/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.90.0
  Forc version: 0.60.0
  Fuel-Core version: 0.30.0
*/

export type { SRC721ContractAbi } from './SRC721ContractAbi.js';

export { SRC721ContractAbi__factory } from './factories/SRC721ContractAbi__factory.js';
